name: "Redis Package Tests"
description: "Run Redis package tests using shunit2 in a QEMU VM"

inputs:
  qemu_dir:
    description: "Directory containing QEMU scripts and environment"
    required: true
  redis_rpm_files:
    description: "Space-separated list of Redis RPM files to install"
    required: false
    default: ""
  test_timeout:
    description: "Timeout for test execution in seconds"
    required: false
    default: "3600"

runs:
  using: "composite"
  steps:
    - name: Upload test files to VM
      shell: bash
      run: |
        # Create tests directory in VM
        ${{ inputs.qemu_dir }}/ssh qemu "mkdir -p /tmp/redis-tests"

        # Upload the test script
        echo "Uploading package_tests.sh..."
        ${{ inputs.qemu_dir }}/scp ${{ github.action_path }}/package_tests.sh qemu:/tmp/redis-tests/

        # Upload shunit2 framework
        echo "Uploading shunit2..."
        ${{ inputs.qemu_dir }}/scp ${{ github.action_path }}/shunit2 qemu:/tmp/redis-tests/

        # Make test script executable
        ${{ inputs.qemu_dir }}/ssh qemu "chmod +x /tmp/redis-tests/package_tests.sh"

    - name: Run Redis package tests
      shell: ${{ inputs.qemu_dir }}/shell {0}
      run: |
        cd /tmp/redis-tests

        # Set environment variable for RPM files if provided
        if [ -n "${{ inputs.redis_rpm_files }}" ]; then
          export REDIS_RPM_INSTALL_FILES="${{ inputs.redis_rpm_files }}"
          echo "REDIS_RPM_INSTALL_FILES set to: ${{ inputs.redis_rpm_files }}"
        else
          echo "No Redis RPM files specified"
        fi

        # Run the tests with timeout
        echo "Starting Redis package tests..."
        timeout ${{ inputs.test_timeout }} ./package_tests.sh

        echo "Redis package tests completed successfully"